.PHONY: clean All

All:
	@echo "----------Building project:[ lofe - Debug ]----------"
	@$(MAKE) -f  "lofe.mk"
clean:
	@echo "----------Cleaning project:[ lofe - Debug ]----------"
	@$(MAKE) -f  "lofe.mk" clean
